// prob_044.rs

// Problem 44
// 
// Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
// 
// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
// 
// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
// 
// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal
// and D = |Pk − Pj| is minimised; what is the value of D?

// import standard library types
use std::time::Instant;
use std::collections::HashSet;

// Calculate pentagonal number P(n)
fn P(n: i32) -> i32 {
    let result: i32 = n * (3 * n - 1) / 2;
    result
}

// Solve the problem
fn solve() -> i32 {
    println!("Go go go!");
    
    // Since we plan to change result, we need to make it mutable using "mut"
    let mut result: i32 = 1_000_000_000;
    
    let max_n: i32  = 3_000;
    
    println!("max_n: {max_n}");
    
    // get pentagonal numbers
    let mut pentagonal_nums_vec: Vec<i32> = Vec::new();
    for n in 1..(max_n+1) {
        pentagonal_nums_vec.push(P(n));
    }
    // convert Vec into HashSet for very fast membership checks
    let pentagonal_nums_set: HashSet<_> = pentagonal_nums_vec.iter().cloned().collect();
    
    // print pentagonal numbers
    //for (i, p) in pentagonal_nums_vec.iter().enumerate() {
    //    let n = i + 1;
    //    println!("P({n}) = {p}");
    //}

    // search for pairs of pentagonal numbers that meet the requirements
    // record the minimal difference
    for i in 0..max_n {
        for j in (i+1)..max_n {
            // calculate the sum and difference
            let p_sum  = pentagonal_nums_vec[i as usize] + pentagonal_nums_vec[j as usize];
            let p_diff = pentagonal_nums_vec[j as usize] - pentagonal_nums_vec[i as usize];
            // require that the sum and difference are pentagonal numbers
            // Note: Membership checks are much faster using HashSets compared to Vecs!!
            if pentagonal_nums_set.contains(&p_sum) && pentagonal_nums_set.contains(&p_diff) {
                if p_diff < result {
                    result = p_diff;
                }
                println!("({i}, {j}): sum = {p_sum}, diff = {p_diff}");
            }
        }
    }

    result
}

// This is the main function.
fn main() {
    let start_time = Instant::now();

    let answer: i32 = solve();

    let end_time = Instant::now();

    let run_time = end_time.duration_since(start_time);

    println!("answer: {answer}");
    println!("run time: {:.2?}", run_time);
}

