# prob_002.py

# Problem 2
#
# Even Fibonacci Numbers
# 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
# 

def solve(max_val):
    s  = 0
    x1 = 1
    x2 = 2
    x3 = x1 + x2
    s += x2
    while x3 <= max_val:
        if x3 % 2 == 0:
            s += x3
        x1 = x2
        x2 = x3
        x3 = x1 + x2
    return s

x = solve(4000000)
print(x)

